language: java

install:
  - chmod a+rx .travis/*.sh
  - .travis/setup-environment.sh

env:
  global:
    - JAVA_HOME=$HOME/bin/oracle-jdk-1.8.0_40
    - MAVEN_HOME=$HOME/bin/apache-maven-3.3.1
    - PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$PATH
  
cache:
  directories:
  - $HOME/bin
  - $HOME/.m2
